development:
  adapter: postgresql
  encoding: unicode
  database: nba-api
  pool: 5
  timeout: 5000
  port: 7654

test:
  adapter: postgresql
  encoding: unicode
  database: nba-api
  pool: 5
  timeout: 5000
  port: 7654